dataset:
  resize: [224, 224]
  point_cloud_points: 2048 # Number of points to sample/keep
  cscan_size: [256, 256]

model:
  image_encoder: "vit_base_patch16_224"
  point_dim: 3
  metadata_dim: 5
  latent_dim: 512
  transformer_layers: 4
  transformer_heads: 8
  merged_dim: 1536

training:
  batch_size: 16
  epochs: 100
  lr: 0.0001
  weight_decay: 0.01
